# Ergogen config file for TEMPORAL keyboard

# TEMPORAL, by curtis bollinger - @curbol
# https://github.com/curbol/temporal
# v1 - fall 2025

# ergogen help: https://flatfootfox.com/ergogen-part1-units-points/

# NOTE: the mcu and display footprint files have been edited to alter drill size to 0.85mm. Build from the footprints on the github repo, not ergogen's web client.

meta:
  engine: 4.1.0
  version: 1.0
  author: curtis bollinger
  url: https://github.com/curbol/temporal

units:
  # Proxy Spacing Variables
  kx: cx #choc spaced
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2

  # Vertical offset of mcu area items
  voff: 7

  # Pinky splay angles
  spang: 8
  pinksprd: 0.5

  standoff_size: 5 # Size for standoff holes on pcb
  screen_standoff_size: 2

  # Top center
  hole1_x: -0.5 kx - 1
  hole1_y: -0.5 ky + 0.5

  # Top right
  hole2_x: -0.52 kx
  hole2_y: -0.35 ky

  # Right Thumb
  hole3_x: 0.5 kx + 0.6
  hole3_y: 0.0 ky - 0.5

  # Left Thumb
  hole4_x: 0kx - 0.5
  hole4_y: -0.6 ky

  # Far Left
  hole5_x: -0.5 kx - 0.6
  hole5_y: -0.6 ky + 1.5

  wall_thickness: 1.2 # Account for the thickness in 3D printed case/plate
  print_fit_tolerance: 0.2 # Give the case some overlap beyond pcb

  # Display correct choc sizing
  $default_width: 18
  $default_height: 17

points:
  zones:
    finger:
      anchor.shift: [50, -100] # Fix KiCad placement
      key:
        padding: 1ky
        spread: 1kx
      columns:
        extra: # Additional outer keys, inspired by KLOR
          rows.bottom.skip: true
          rows.top.skip: false
          key.splay: spang
          key.column_net: col_extra
        pinky:
          key.stagger: 0.5ky
          # key.splay: spang # Comment this line out if using the 'extra' key above
          key.column_net: col_pinky
        ring:
          key.stagger: 0.35ky
          key.splay: -spang/2
          key.spread: 1kx + pinksprd # Avoid collision on splayed col?
          key.column_net: col_ring
        middle:
          key.stagger: 0.25ky
          key.splay: -spang/2
          key.spread: 1kx + pinksprd # Avoid collision on splayed col?
          key.column_net: col_middle
        index:
          key.stagger: -0.2ky
          key.column_net: col_index
        inner:
          key.stagger: -0.15ky
          key.column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top

    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: finger_middle_bottom
        shift: [0.4kx, -1.3ky]
      columns:
        encoder:
          key.name: thumb_enc
          key.column_net: col_ring
        near:
          key.splay: -9
          key.origin: [-0.5kx, -0.5ky]
          key.name: thumb_near
          key.column_net: col_middle
        mid:
          key.splay: -9
          key.origin: [-0.5kx, -0.5ky]
          key.name: thumb_mid
          key.column_net: col_index
        far:
          key.splay: -9
          key.origin: [-0.5kx, -0.5ky]
          key.name: thumb_far
          key.column_net: col_inner
      rows:
        thumb:
          row_net: row_thumb

outlines:
  # Just the keys
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]

  key_plugs:
    - what: rectangle
      where: true
      size: [13.8, 13.8]

  finger_section:
    - what: rectangle
      where:
        - finger_pinky_top
        - finger_pinky_home
        - finger_ring_top
        - finger_ring_home
        - finger_ring_bottom
      size: [px, py]
      adjust:
        shift: [0.5px, 0py]

  thumb_section:
    - what: polygon
      points:
        - ref: finger_inner_bottom
          shift: [0.5px, -0.5py]

        - ref: thumb_far
          shift: [-0.5px, 0.5py]
        - ref: thumb_far
          shift: [0.5px, 0.5py]
        - ref: thumb_far
          shift: [0.5px, -0.5py]
        - ref: thumb_far
          shift: [-0.5px, -0.5075py]

        - ref: thumb_near
          shift: [0.5px, -0.5py]

        - ref: thumb_enc
          shift: [0.5px, -0.5py]
        - ref: thumb_enc
          shift: [-0.5px, -0.5py]
        - ref: thumb_enc
          shift: [-0.5px, 1py]
        - ref: thumb_enc
          shift: [0.5px, 1py]

  mcu_section:
    - what: rectangle
      where:
        - ref: finger_inner_top
          shift: [19.5, -20 - voff]
      size: [22, 62]

  key_thumb_outline: [raw, finger_section, thumb_section]
  key_thumb_mcu_outline: [key_thumb_outline, mcu_section]
  board_outline_raw:
    - name: key_thumb_mcu_outline
      fillet: 1

  board_outline:
    - name: board_outline_raw
      expand: 0.1

  # Combination preview showing outline and keys.
  all_key_outline:
    - name: board_outline
    - operation: subtract
      name: keys

  top_plate:
    - name: key_thumb_outline
    - operation: subtract
      name: key_plugs
      fillet: 1

  back_plate:
    - name: board_outline
      expand: wall_thickness + print_fit_tolerance
      fillet: 1

pcbs:
  TEMPORAL:
    template: kicad8
    outlines:
      main:
        outline: board_outline
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          include_corner_marks: true
          include_keycap: true
          keycap_height: 16.5
          keycap_width: 17.5
          reversible: true
          hotswap: true
          choc_v2_support: false
          trace_width: 0.25
          via_size: 0.8
          via_drill: 0.4

      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: true
          include_traces_vias: true
          via_size: 0.8
          via_drill: 0.4
        adjust:
          shift: [0, -5]

      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          - ref: thumb_enc
        params:
          reversible: true
          include_plated_mounting_holes: false
          include_momentary_switch_pads: true
          smd_momentary_switch: true
          A: encoder_a # Left pin
          C: GND # Center pin
          B: encoder_b # Right pin
          S1: col_ring # Switch pin 1
          S2: encoder_thumb # Switch pin 2

      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          - ref: finger_inner_home
            shift: [19.8, 10.8 - voff]
        params:
          reversible: true
          reverse_mount: true
          show_silk_labels: false
          # Finger rows
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          # Finger columns
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
          P21: col_extra
          # Encoder (using available pins)
          P0: encoder_a
          P1: encoder_b
          # SPI for nice!view
          P8: MOSI
          P9: SCK
          P10: CS

      display:
        what: ceoloide/display_nice_view
        params:
          reversible: true
          include_labels: false
        where:
          - ref: finger_inner_home
            shift: [19.8, 7.5 - voff]

      battery:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: true
          include_traces_vias: true
          via_size: 0.8
          via_drill: 0.4
        where:
          - ref: finger_inner_home
            shift: [23.5, -14.5 - voff]
            rotate: -90

      power:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
          include_traces_vias: true
          via_size: 0.8
          via_drill: 0.4
        where:
          - ref: finger_inner_home
            shift: [27.9, -18.5 - voff]
            rotate: 0

      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          reversible: true
          include_traces_vias: true
          via_size: 0.8
          via_drill: 0.4
        where:
          - ref: finger_inner_home
            shift: [28.3, -10.2 - voff]
            rotate: -90

      temporal:
        what: ceoloide/utility_text
        where:
          - ref: finger_middle_bottom
            shift: [0, -0.65ky]
        params:
          text: "TEMPORAL"
          height: 2
          width: 2
          knockout: true
          reversible: true

      #ver:
      #  what: ceoloide/utility_text
      #  where:
      #    - ref: finger_index_home
      #      shift: [0.5kx, -0.5ky +1.45]
      #  params:
      #    text: "v 2"
      #    reversible: true

      curbol:
        what: ceoloide/utility_text
        where:
          - ref: thumb_far
            shift: [0, -3]
        params:
          text: "by curbol"
          reversible: true

      hole_1:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_middle_top
            shift: [hole1_x, hole1_y]

        params:
          hole_size: standoff_size
          hole_drill: standoff_size
      hole_2:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_inner_top
            shift: [hole2_x, hole2_y]
        params:
          hole_size: standoff_size
          hole_drill: standoff_size
      hole_3:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: thumb_mid
            shift: [hole3_x, hole3_y]
        params:
          hole_size: standoff_size
          hole_drill: standoff_size
      hole_4:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_index_bottom
            shift: [hole4_x, hole4_y]
        params:
          hole_size: standoff_size
          hole_drill: standoff_size
      hole_5:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_ring_home
            shift: [hole5_x, hole5_y]
        params:
          hole_size: standoff_size
          hole_drill: standoff_size

      # MCU cover holes
      hole_screen_L:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_inner_bottom
            shift: [0.5 kx + 4 + 0, -0.5 ky - 0]
        params:
          hole_size: screen_standoff_size
          hole_drill: screen_standoff_size
      hole_screen_R:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_inner_bottom
            shift: [0.5 kx + 4 + 14, -0.5 ky - 6.5 - 0]
        params:
          hole_size: screen_standoff_size
          hole_drill: screen_standoff_size

  TEMPORAL-BACKPLATE:
    template: kicad8
    outlines:
      main:
        outline: back_plate
    footprints:
      hole_1:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_middle_top
            shift: [hole1_x, hole1_y]
      hole_2:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_inner_top
            shift: [hole2_x, hole2_y]
      hole_3:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: thumb_mid
            shift: [hole3_x, hole3_y]
      hole_4:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_index_bottom
            shift: [hole4_x, hole4_y]
      hole_5:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_ring_home
            shift: [hole5_x, hole5_y]

  TEMPORAL_TOPPLATE:
    template: kicad8
    outlines:
      main:
        outline: top_plate
    footprints:
      hole_1:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_middle_top
            shift: [hole1_x, hole1_y]
      hole_2:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_inner_top
            shift: [hole2_x, hole2_y]
      hole_3:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: thumb_mid
            shift: [hole3_x, hole3_y]
      hole_4:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_index_bottom
            shift: [hole4_x, hole4_y]
      hole_5:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: finger_ring_home
            shift: [hole5_x, hole5_y]
